#!/bin/ash
logpath='/frpc.log'
echo "start " >$logpath
model=$(cat /proc/xiaoqiang/model)
setconfig model $model
type=$(getconfig type)
if [[ -z "$type" ]]; then
	#statements
	type="%E7%AE%80%E5%8D%95%E8%AE%BE%E7%BD%AE"
	setconfig type $type
	setconfig enable on
fi

if [[ "$type" == "%E7%AE%80%E5%8D%95%E8%AE%BE%E7%BD%AE" ]]; then
	#statements
	getconfig baseini >/baseini
	cat /baseini|/bin/urldecode >frpc.ini
else
	getconfig advanceini >/advanceini
	cat /advanceini|/bin/urldecode >frpc.ini
fi


app_path='/bin/frpc'

if [ "$model" == "R1D" -o "$model" == "R2D" -o "$model" == "R3D"  ]; then
	app_path='/bin/frpc'
elif [ "$model" == "R3" -o "$model" == "R3P" -o "$model" == "R3G" -o "$model" == "R1CM" ]; then
	app_path='/bin/frpc_mips'
fi

#start app_path
#if [[ -f "/frpc.ini" ]]; then
#    $app_path -c /frpc.ini > $logpath 2>&1
#fi

PID=$(pidof $app_path)

echo "start $app_path : $PID" >>$logpath
enable="on"
while [[ "$enable" == "on" ]]; do
	PID=$(pidof $app_path)
	echo "pid of $app_path : $PID" >>$logpath
	#statements
	enable=$(getconfig enable)
	echo "enable: $enable" >>$logpath
	sleep 3
done

