#!/bin/ash
pidof(){
	ps|grep "$@" |grep -v grep|awk '{print $1}'
}

getconfig() {
	grep "key$1" /etc/plugin_config |awk -F '=' '{print $2}'|awk '{print substr($1,2)}'|awk '{print substr($1,1,length($1)-2)}'
}

setconfig() {
	key="key$1";
	val=$2;
	newstr="$key = \"$val\";"
	config_path="/etc/plugin_config";
	if [[ -z "$(grep $key $config_path)" ]]; then
		echo $newstr >> $config_path
	else
		oldstr=$(grep $key $config_path)
		sed -i "s/$oldstr/$newstr/g" $config_path
	fi
}

urldecode(){
	awk 'BEGIN{for(i=0;i<10;i++)hex[i]=i;hex["A"]=hex["a"]=10;hex["B"]=hex["b"]=11;hex["C"]=hex["c"]=12;hex["D"]=hex["d"]=13;hex["E"]=hex["e"]=14;hex["F"]=hex["f"]=15;}{gsub(/\+/," ");i=$0;while(match(i,/%../)){;if(RSTART>1);printf"%s",substr(i,1,RSTART-1);printf"%c",hex[substr(i,RSTART+1,1)]*16+hex[substr(i,RSTART+2,1)];i=substr(i,RSTART+RLENGTH);}print i;}'
}
initInFirstRun(){
	type="%E7%AE%80%E5%8D%95%E8%AE%BE%E7%BD%AE"
	setconfig type $type
	setconfig enable on

}

model=$(cat /proc/xiaoqiang/model)
setconfig model $model

#init config
initConfig() {
	type=$(getconfig type)
	if [[ -z "$type" ]]; then
		initInFirstRun
	fi

	if [[ "$type" == "%E7%AE%80%E5%8D%95%E8%AE%BE%E7%BD%AE" ]]; then
		getconfig baseini|urldecode >/frpc.ini
	else
		getconfig advanceini|urldecode >/frpc.ini
	fi
}

initConfig

LAST_CONFIG_CHANGE=`ls -e /etc/plugin_config |awk '{print $10"-"$7"-"$8" "$9}'`

#setconfig enable on
enable="on"
while [[ "$enable" == "on" ]]; do
	enable=$(getconfig enable)
	if [ "$LAST_CONFIG_CHANGE" != "`ls -e /etc/plugin_config |awk '{print $10"-"$7"-"$8" "$9}'`" ]; then
		initConfig
		#reload frpc
		/frpc reload 
	fi
sleep 3
done

